# Generated by Django 5.1.5 on 2025-02-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0003_alter_games_icon_alter_games_name'),
        ('indicators', '0002_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('icon', models.ImageField(upload_to='teams/teams_images/')),
                ('founding_date', models.DateTimeField(verbose_name='Дата основания')),
                ('team_history', models.TextField(verbose_name='История команды')),
                ('prize', models.IntegerField(verbose_name='Призовые')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.games')),
                ('indicators', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='indicators.indicators')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.players')),
            ],
            options={
                'verbose_name': 'Название команды',
                'verbose_name_plural': 'Названия команд',
            },
        ),
    ]
