# Generated by Django 5.1.5 on 2025-02-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_players_team'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='player',
        ),
        migrations.AddField(
            model_name='teams',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='players.players'),
        ),
    ]
