# Generated by Django 5.1.5 on 2025-03-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teams_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='icon_country',
            field=models.ImageField(blank=True, upload_to='teams/teams_images/country/'),
        ),
    ]
