# Generated by Django 5.1.5 on 2025-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_teams_icon_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='site',
            field=models.CharField(default='site.ru', max_length=100, verbose_name='Сайт'),
        ),
    ]
