# Generated by Django 5.1.5 on 2025-03-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_teams_icon_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='teams/teams_images/'),
        ),
    ]
