# Generated by Django 5.1.5 on 2025-04-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='news/news_images/'),
        ),
    ]
