# Generated by Django 5.1.5 on 2025-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wins', models.IntegerField(verbose_name='Количество побед')),
                ('loses', models.IntegerField(verbose_name='Количество поражений')),
                ('draws', models.IntegerField(verbose_name='Количество ничей')),
                ('achievements', models.TextField(verbose_name='Достижения')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
            },
        ),
    ]
