# Generated by Django 5.1.5 on 2025-03-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_alter_indicators_match_alter_indicators_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='loses',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='wins',
        ),
    ]
