# Generated by Django 5.1.5 on 2025-03-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_remove_indicators_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicators',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='indicators',
            name='draws',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ничей'),
        ),
        migrations.AddField(
            model_name='indicators',
            name='loses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество поражений'),
        ),
        migrations.AddField(
            model_name='indicators',
            name='wins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество побед'),
        ),
    ]
