# Generated by Django 5.1.5 on 2025-02-16 19:25

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='date',
        ),
        migrations.AddField(
            model_name='tournaments',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 12, 0), verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.teams'),
        ),
    ]
