# Generated by Django 5.1.5 on 2025-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_teams_players'),
        ('tournaments', '0003_alter_tournaments_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='team',
        ),
        migrations.AddField(
            model_name='tournaments',
            name='teams',
            field=models.ManyToManyField(blank=True, to='teams.teams'),
        ),
    ]
