# Generated by Django 5.1.5 on 2025-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100, verbose_name='Ник')),
                ('fio', models.CharField(max_length=250, verbose_name='ФИО')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('photo', models.ImageField(upload_to='players/players_images/')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
