# Generated by Django 5.1.5 on 2025-02-19 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='players',
            name='icon_country',
            field=models.ImageField(blank=True, upload_to='players/players_images/country/'),
        ),
        migrations.AddField(
            model_name='players',
            name='sum_prize',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма призовых'),
        ),
        migrations.AlterField(
            model_name='players',
            name='photo',
            field=models.ImageField(blank=True, upload_to='players/players_images/'),
        ),
        migrations.AlterField(
            model_name='players',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.teams'),
        ),
    ]
