# Generated by Django 5.1.5 on 2025-02-19 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_players_description_players_icon_country_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_in_team', to='teams.teams'),
        ),
    ]
