# Generated by Django 5.1.5 on 2025-03-03 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_icon_alter_games_name'),
        ('players', '0004_alter_players_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.games'),
        ),
    ]
