# Generated by Django 5.1.5 on 2025-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_players_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='draws',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество ничей'),
        ),
        migrations.AddField(
            model_name='players',
            name='loses',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество поражений'),
        ),
        migrations.AddField(
            model_name='players',
            name='wins',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество побед'),
        ),
    ]
