# Generated by Django 5.1.5 on 2025-03-05 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_players_age_alter_players_datebirth'),
        ('teams', '0007_teams_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата вступления')),
                ('date_left', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='players.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teams')),
            ],
            options={
                'unique_together': {('player', 'team')},
            },
        ),
    ]
