# Generated by Django 5.1.5 on 2025-04-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_alter_playerteamhistory_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='fio',
            field=models.CharField(max_length=250, unique=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='players',
            name='icon_country',
            field=models.ImageField(upload_to='players/players_images/country/'),
        ),
        migrations.AlterField(
            model_name='players',
            name='nickname',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='players',
            name='photo',
            field=models.ImageField(upload_to='players/players_images/'),
        ),
    ]
