# Generated by Django 5.1.5 on 2025-03-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='fio',
        ),
    ]
