# Generated by Django 5.1.5 on 2025-03-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_customuser_delete_userprofiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
