# Generated by Django 5.1.5 on 2025-04-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='entry_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
