# Generated by Django 5.1.5 on 2025-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0008_emailverificationcode_entry_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='entry_permissions',
            field=models.BooleanField(default=True),
        ),
    ]
