# Generated by Django 5.1.5 on 2025-04-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0010_alter_emailverificationcode_entry_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='entry_permissions',
        ),
    ]
