# Generated by Django 5.1.5 on 2025-02-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='status',
        ),
    ]
