# Generated by Django 5.1.5 on 2025-02-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название игры')),
                ('icon', models.ImageField(upload_to='games/static/games/icons/')),
            ],
            options={
                'verbose_name': 'Название игры',
                'verbose_name_plural': 'Название игр',
            },
        ),
    ]
