# Generated by Django 5.1.5 on 2025-02-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Название игры', 'verbose_name_plural': 'Игры'},
        ),
    ]
