# Generated by Django 5.1.5 on 2025-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_games_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='icon',
            field=models.ImageField(upload_to='games/games_icon/'),
        ),
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название игры'),
        ),
    ]
