# Generated by Django 5.1.5 on 2025-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_icon_alter_games_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='games/games_icon/'),
        ),
    ]
